FROM ppc64le/ubuntu:focal

ARG PLATFORM=ppc64le
RUN apt update
RUN apt install -y gnupg
# Script to choose Python version
# Installer script for Pythons
COPY build_install_pythons.sh /

# Install Pythons and matching pips
RUN bash build_install_pythons.sh && rm build_install_pythons.sh

# Install manylinux1 libraries. See:
# https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy
# https://github.com/multi-build/multibuild/issues/106
RUN apt-get update && \
        apt-get install -y libncurses5 libgcc1 libstdc++6 libc6 libx11-6 libxext6 \
        libxrender1 libice6 libsm6 libgl1-mesa-glx libglib2.0-0

# Get virtualenv
RUN pip3.6 install --user virtualenv

# Run Python selection on way into image
COPY choose_python.sh /usr/bin/
ENTRYPOINT ["/usr/bin/choose_python.sh"]
